name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  make:
    strategy:
      matrix:
        target: [GZIP, NCOM, BC, YPSV, POLY, PEG, YAML1, YAML2, TIFF]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Install Bear
        run: sudo apt install -y bear

      - name: Install GCC
        run: sudo apt install -y gcc-12 gcc-12-multilib

      - name: Install Clang
        run: |
          sudo apt install -y lsb-release wget software-properties-common gnupg
          curl -sSf https://apt.llvm.org/llvm.sh | sudo bash -s -- 17 all

      - name: Install dependencies
        run: sudo apt install -y automake bison flex libgdbm-dev

      - name: Make with gcc/g++
        run: |
          make clean
          make CC=gcc-12 CXX=g++-12 ${{matrix.target}}

      - name: Make with clang/clang++
        run: |
          make clean
          make CC=clang-17 CXX=clang++-17 ${{matrix.target}}
